port:
  http: 8089
  tcp: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.28.189:3306/fire-gms?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: firetest
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
